# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
parameters:
    unsignedPipelineResource: null
    unsignedArtifactName: null
    signedArtifactName: null

jobs:
    - job: ${{ parameters.signedArtifactName }}
      pool:
          vmImage: 'ubuntu-18.04'
      steps:
          - template: ../../install-node-prerequisites.yaml

          - task: DownloadPipelineArtifact@2
            inputs:
                source: 'specific'
                runVersion: 'specific'
                project: $(resources.pipeline.${{ parameters.unsignedPipelineResource }}.projectID)
                pipeline: $(resources.pipeline.${{ parameters.unsignedPipelineResource }}.pipelineID)
                runId: $(resources.pipeline.${{ parameters.unsignedPipelineResource }}.runID)
                artifact: ${{ parameters.unsignedArtifactName }}
                path: '$(System.DefaultWorkingDirectory)/signing-in-progress/${{ parameters.signedArtifactName }}'

          - template: sign-release-package.yaml
            parameters:
                filePattern: '*.AppImage'
                platform: linux
                signedArtifactName: ${{ parameters.signedArtifactName }}
                inlineSignParams: |
                    [
                        {
                            "keyCode": "CP-450779-Pgp",
                            "operationSetCode": "PgpClearSign",
                            "parameters": [],
                            "toolName": "sign",
                            "toolVersion": "1.0"
                        }
                    ]
